### ISSUE TITLE
Update ProveIt website to be compatible with jQuery 1.9 without jQuery Migrate

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#190] opened 2014-06-29 05:01 UTC
It uses jQuery hashchange, which currently does not support jQuery 1.9 (though there are open pull requests, e.g. https://github.com/cowboy/jquery-hashchange/pull/40).

The known issue is use of jQuery.browser; I haven't checked it for others.

Until they merge that pull request, I may need to maintain a temporary fork of jQuery hashchange.

Note, MultimediaViewer has the [same issue](https://bugzilla.wikimedia.org/show_bug.cgi?id=66098)

**Comment by sophivorus** [comment] 2016-04-03 08:45
Closing as duplicate of #205

**Closed by sophivorus** 2016-04-03 08:45 UTC
Labels: Component-Website, Maintainability, Priority-High
