### ISSUE TITLE
Make expandable author and editor UIs

### ISSUE THREAD

**Issue by mattflaschen** [proveit-js/proveit#163] opened 2014-02-18 05:24 UTC
_From [matthew.flaschen@gatech.edu](https://code.google.com/u/108647890027017428365/) on April 08, 2013 23:59:02_

Lua now allows an arbitrary number of authors and editors.  Besides simply supporting that in the labels ( issue 165 ), this is a good opportunity to make a better author UI.

I think this should be oriented around last and first name fields, with an easy way to add another one.  The simplest way is to allow adding author rows, but there may be other UI ideas.

_Original issue: http://code.google.com/p/proveit-js/issues/detail?id=166_

**Comment by lfschenone** [comment] 2016-03-24 21:02
Duplicate of #162

**Closed by lfschenone** 2016-03-24 21:02 UTC
Labels: enhancement, imported, Priority-Medium
